### ISSUE TITLE
new ItemType are not given Permission to the service that created them.

### ISSUE THREAD

**Issue by tomecho** [umts/aggressive-epsilon#18]

**Comment by dfaulken** [comment]
Probably the simplest way to go here would be to add a `creator` column to `ItemType` like on `Reservation`.

Then an after-create hook on item types that establishes write permissions for the service which created them.

**Comment by dfaulken** [comment]
And BTW, it won't be possible for any service to create their own first item type out of the box. This is intentional. Services can only create new item types if they already have write access to another item type. So for most cases, the maintainers of aggressive-epsilon would have to manually establish the first item type for a new service.

**Comment by tomecho** [comment]
just read these comments now, logan and I had thought of that but I just ended up going and creating a new permission in the itemtype create method of the controller.  Oh well, Ill change this in the morning.
